name: Run

on:
  workflow_call:
    inputs:
      min:
        description: "min"
        required: false
        type: string
      max:
        description: "max"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.min }}-${{ inputs.max }}
