name: Run

on:
  workflow_call:
    inputs:
      from:
        description: "from"
        required: true
        type: string
      to:
        description: "to"
        required: false
        type: string
      ignore:
        description: "ignore"
        required: false
        type: string
      script:
        description: "script"
        required: true
        type: string

jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.fetch.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: fetch
        env:
          INPUT_FROM: ${{ inputs.from }}
          INPUT_TO: ${{ inputs.to }}
          INPUT_IGNORE: ${{ inputs.ignore }}
        with:
          retries: 3
          script: |
            const from = core.getInput("from", { required: true });
            const to = core.getInput("to");
            const ignore = core.getMultilineInput("ignore");
            const response = await fetch("https://piston-meta.mojang.com/mc/game/version_manifest_v2.json");
            const manifest = await response.json();
            const versions = [];
            let include = to === "";
            for (const version of manifest.versions) {
              const id = version.id;
              if (id === to) {
                include = true;
              }
              if (include && !ignore.includes(id)) {
                versions.push(id);
              }
              if (id === from) {
                break;
              }
            }
            console.log(versions);
            return versions;
  check:
    needs: fetch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.fetch.outputs.versions) }}
    steps:
      - uses: actions/checkout@v3
      - uses: mcenv/setup-minecraft@v3
        id: minecraft
        with:
          version: ${{ matrix.version }}
      - uses: actions/github-script@v6
        id: check
        env:
          MINECRAFT: ${{ steps.minecraft.outputs.version }}
        with:
          script: ${{ inputs.script }}
