name: Update

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          git config --global user.name "mcenv"
          git config --global user.email "mcenv@users.noreply.github.com"
          git worktree add dist dist
          npm install
          npm run package
          cd dist
          mv ../action.yml .
          mv ../LICENSE .
          mv ../README.md .
          git add .
          git commit --message "Update"
          git push origin dist
